image: google/cloud-sdk:latest

variables:
  PROJECT_ID: lefri-ai
  SERVICE_NAME: lefri-platform
  REGION: us-central1

stages:
  - deploy

deploy:
  stage: deploy
  script:
    # Configurar credenciales de Google Cloud
    - echo $GCP_SERVICE_ACCOUNT_KEY | base64 -d > /tmp/gcp-key.json
    - gcloud auth activate-service-account --key-file=/tmp/gcp-key.json
    - gcloud config set project $PROJECT_ID

    # Ejecutar script de despliegue
    - chmod +x ./scripts/deploy.sh
    - ./scripts/deploy.sh

  only:
    - main
