steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/lefri-app', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/lefri-app']
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'lefri-app'
  - '--image'
  - 'gcr.io/$PROJECT_ID/lefri-app'
  - '--region'
  - '${_REGION}'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
  - '--memory'
  - '2Gi'
  - '--cpu'
  - '2'
  - '--min-instances'
  - '1'
  - '--max-instances'
  - '10'
  - '--set-env-vars'
  - 'NODE_ENV=production,MONGODB_URI=${_MONGODB_URI},GOOGLE_OAUTH_CLIENT_ID=${_GOOGLE_OAUTH_CLIENT_ID},GOOGLE_OAUTH_CLIENT_SECRET=${_GOOGLE_OAUTH_CLIENT_SECRET},GOOGLE_OAUTH_REDIRECT_URI=${_GOOGLE_OAUTH_REDIRECT_URI},GEMINI_API_KEY=${_GEMINI_API_KEY}'
substitutions:
  _REGION: us-central1
  _MONGODB_URI: ${MONGODB_URI}
  _GOOGLE_OAUTH_CLIENT_ID: ${GOOGLE_OAUTH_CLIENT_ID}
  _GOOGLE_OAUTH_CLIENT_SECRET: ${GOOGLE_OAUTH_CLIENT_SECRET}
  _GOOGLE_OAUTH_REDIRECT_URI: ${GOOGLE_OAUTH_REDIRECT_URI}
  _GEMINI_API_KEY: ${GEMINI_API_KEY}
images:
- 'gcr.io/$PROJECT_ID/lefri-app'
