steps:
  # Limpiar node_modules y package-lock.json
  - name: 'node:18'
    entrypoint: npm
    args: ['cache', 'clean', '--force']
    id: 'clean-cache'

  # Instalar dependencias
  - name: 'node:18'
    entrypoint: npm
    args: ['install', '--platform=linux', '--arch=x64']
    id: 'install-deps'

  # Instalar dependencias específicas de Rollup para Linux
  - name: 'node:18'
    entrypoint: npm
    args: ['install', '@rollup/rollup-linux-x64-gnu']
    id: 'install-rollup-deps'

  # Construir la aplicación
  - name: 'node:18'
    entrypoint: npm
    args: ['run', 'build']
    id: 'build-app'

  # Construir la imagen Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/lefri-platform:$_TAG', '.']
    id: 'build-image'

  # Subir la imagen a Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/lefri-platform:$_TAG']
    id: 'push-image'

  # Desplegar en Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'lefri-platform'
      - '--image'
      - 'gcr.io/$PROJECT_ID/lefri-platform:$_TAG'
      - '--region'
      - '$_REGION'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--set-env-vars'
      - 'NODE_ENV=production,MONGODB_URI=$_MONGODB_URI,GOOGLE_OAUTH_CLIENT_ID=$_GOOGLE_OAUTH_CLIENT_ID,GOOGLE_OAUTH_CLIENT_SECRET=$_GOOGLE_OAUTH_CLIENT_SECRET,GOOGLE_OAUTH_REDIRECT_URI=$_GOOGLE_OAUTH_REDIRECT_URI,GEMINI_API_KEY=$_GEMINI_API_KEY'
      - '--timeout'
      - '300s'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--execution-environment'
      - 'gen2'
      - '--tag'
      - '$_TAG'

images:
  - 'gcr.io/$PROJECT_ID/lefri-platform:$_TAG'

substitutions:
  _TAG: latest
  _REGION: us-central1
  _MONGODB_URI: ${_MONGODB_URI}
  _GOOGLE_OAUTH_CLIENT_ID: ${_GOOGLE_OAUTH_CLIENT_ID}
  _GOOGLE_OAUTH_CLIENT_SECRET: ${_GOOGLE_OAUTH_CLIENT_SECRET}
  _GOOGLE_OAUTH_REDIRECT_URI: ${_GOOGLE_OAUTH_REDIRECT_URI}
  _GEMINI_API_KEY: ${_GEMINI_API_KEY}

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
  dynamicSubstitutions: true
  env:
    - 'CLOUDSDK_COMPUTE_REGION=${_REGION}'
    - 'CLOUDSDK_CORE_PROJECT=${PROJECT_ID}'
