name: Deploy to Cloud Run

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  PROJECT_ID: lefri-ai
  SERVICE_NAME: lefri-platform
  REGION: us-central1

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Google Auth
      id: auth
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Deploy to Cloud Run
      run: |
        # Decodificar variables de entorno
        export MONGODB_URI=$(echo ${{ secrets.MONGODB_URI_BASE64 }} | base64 -d)
        export GOOGLE_OAUTH_CLIENT_ID=$(echo ${{ secrets.GOOGLE_OAUTH_CLIENT_ID_BASE64 }} | base64 -d)
        export GOOGLE_OAUTH_CLIENT_SECRET=$(echo ${{ secrets.GOOGLE_OAUTH_CLIENT_SECRET_BASE64 }} | base64 -d)
        export GEMINI_API_KEY=$(echo ${{ secrets.GEMINI_API_KEY_BASE64 }} | base64 -d)
        export GOOGLE_OAUTH_REDIRECT_URI=${{ secrets.GOOGLE_OAUTH_REDIRECT_URI }}

        # Ejecutar script de despliegue
        chmod +x ./scripts/deploy.sh
        ./scripts/deploy.sh 